export const COMPANY_NAME = "Grinmove"; //"Grinhome";
export const API_CALL_TIME_OUT = 25000;

export const MAX_RECIEPT_ATTACHEMENTS = 5;

export const NUMBER_OF_PAGINATION_ITEMS = 5;

//LISTING PARAMETERS
export const NEW_AGENT_PROMOTION = "NEW_AGENT_PROMOTION";
export const HOLIDAY_PROMOTION = "HOLIDAY_PROMOTION";

export const LISTING_PARAMS_VALUE_TYPE_DAYS = "DAYS";
export const LISTING_PARAMS_VALUE_TYPE_LISTING_COUNT = "LISTING_COUNT";

//SYSTEM PARAMETERS

export const SYSTEM_PARAMS_PUBLIC_LISTING_PAGE_SIZE =
  "PUBLIC_LISTING_PAGE_SIZE";

//LISTING MODES - WHETHER THE AGENT USE SUBSCRIPTION OR PAY AT LISTING TIME
export const LISTING_MODE_PAY_PER_LISTING = "PAY_PER_LISTING";
export const LISTING_MODE_SUBSCRIPTION = "SUBSCRIPTION";
export const LISTING_MODE_BOTH = "BOTH";

//Distance units
export const distanceUnit = [
  { id: "METER", name: "Meter" },
  { id: "KM", name: "Kilo Meter" },
  { id: "MILE", name: "Mile" },
];

//PATHS
export const PATH_DYNAMIC_PROPERTY = ":propertyId";

//AUTH
export const PATH_SIGNIN = "/signin";
export const PATH_SIGNUP = "/signup";
export const PATH_ADD_PROPERTY = "/list-your-property";
export const PATH_LANDING = "/";
export const PATH_PAGE_NOT_FOUND = "*";

//AGENTs
export const PATH_AGENTS_HOME = "/agents";
export const PATH_AGENTS_SEARCH = "search";
export const PATH_AGENTS_SEARCH_ABSOLUTE = `${PATH_AGENTS_HOME}/${PATH_AGENTS_SEARCH}`;
export const PATH_AGENT_DETAIL = "detail";
export const PATH_AGENT_ID_VARIABLE = ":agentId";
export const PATH_AGENTS_LIST = "list";
export const PATH_AGENTS_LIST_ABSOLUTE = `${PATH_AGENTS_HOME}/${PATH_AGENTS_LIST}`;
export const PATH_AGENTS_ADD = "add";
export const PATH_AGENTS_ADD_ABSOLUTE = `${PATH_AGENTS_HOME}/${PATH_AGENTS_ADD}`;
export const PATH_AGENT_CREATE_INFO = "info";
export const PATH_AGENT_CREATE_INFO_ABSOLUTE = `${PATH_AGENTS_HOME}/${PATH_AGENT_CREATE_INFO}`;
export const PATH_AGENT_LOGO_UPLOAD = "logo/upload";
export const PATH_AGENT_LOGO_UPLOAD_ABSOLUTE = `${PATH_AGENTS_HOME}/${PATH_AGENT_LOGO_UPLOAD}`;

export const PATH_AGENT_CONTACT = "contact/public";
export const PATH_AGENT_CONTACT_ABSOLUTE = `${PATH_AGENTS_HOME}/${PATH_AGENT_CONTACT}`;

// AGENT DASHBOARD
export const PATH_AGENT_DASHBOARD = "/agent/dashboard";
// export const PATH_AGENT_DASHBOARD_ABSOLUTE = `${PATH_AGENTS_HOME}/${PATH_AGENT_DASHBOARD}`;
export const PATH_AGENT_DASHBOARD_STAT = "stat";
export const PATH_AGENT_DASHBOARD_STAT_ABSOLUTE = `${PATH_AGENT_DASHBOARD}/${PATH_AGENT_DASHBOARD_STAT}`;
export const PATH_AGENT_DASHBOARD_AGENT_INFO = "agent-info";
export const PATH_AGENT_DASHBOARD_AGENT_INFO_ABSOLUTE = `${PATH_AGENT_DASHBOARD}/${PATH_AGENT_DASHBOARD_AGENT_INFO}`;

export const PATH_AGENT_DASHBOARD_PROPERTY = "property";
export const PATH_AGENT_DASHBOARD_PROPERTY_ADD = "add";
export const PATH_AGENT_DASHBOARD_PROPERTY_ADD_ABSOLUTE = `${PATH_AGENT_DASHBOARD}/${PATH_AGENT_DASHBOARD_PROPERTY}/${PATH_AGENT_DASHBOARD_PROPERTY_ADD}`;
export const PATH_AGENT_DASHBOARD_PROPERTY_LIST = "list";

//APARTMENT
export const PATH_AGENT_DASHBOARD_APARTMENT_LIST = "apartment/list";
export const PATH_AGENT_DASHBOARD_APARTMENT_LIST_ABSOLUTE = `${PATH_AGENT_DASHBOARD}/${PATH_AGENT_DASHBOARD_PROPERTY}/${PATH_AGENT_DASHBOARD_APARTMENT_LIST}`;
export const PATH_AGENT_DASHBOARD_APARTMENT_EDIT = "apartment/edit";
export const PATH_AGENT_DASHBOARD_APARTMENT_EDIT_ABSOLUTE = `${PATH_AGENT_DASHBOARD}/${PATH_AGENT_DASHBOARD_PROPERTY}/${PATH_AGENT_DASHBOARD_APARTMENT_EDIT}`;
export const PATH_AGENT_DASHBOARD_APARTMENT_DETAIL = "apartment/detail";
export const PATH_AGENT_DASHBOARD_APARTMENT_DETAIL_ABSOLUTE = `${PATH_AGENT_DASHBOARD}/${PATH_AGENT_DASHBOARD_PROPERTY}/${PATH_AGENT_DASHBOARD_APARTMENT_DETAIL}`;

//APARTMENT UNIT
export const PATH_AGENT_DASHBOARD_APARTMENTUNIT_DETAIL = "apartmentunit/detail";
export const PATH_AGENT_DASHBOARD_APARTMENTUNIT_DETAIL_ABSOLUTE = `${PATH_AGENT_DASHBOARD}/${PATH_AGENT_DASHBOARD_PROPERTY}/${PATH_AGENT_DASHBOARD_APARTMENTUNIT_DETAIL}`;
export const PATH_AGENT_DASHBOARD_APARTMENTUNIT_EDIT = "apartmentunit/edit";
export const PATH_AGENT_DASHBOARD_APARTMENTUNIT_EDIT_ABSOLUTE = `${PATH_AGENT_DASHBOARD}/${PATH_AGENT_DASHBOARD_PROPERTY}/${PATH_AGENT_DASHBOARD_APARTMENTUNIT_EDIT}`;

// VILLA
export const PATH_AGENT_DASHBOARD_VILLA_LIST = "villa/list";
export const PATH_AGENT_DASHBOARD_VILLA_LIST_ABSOLUTE = `${PATH_AGENT_DASHBOARD}/${PATH_AGENT_DASHBOARD_PROPERTY}/${PATH_AGENT_DASHBOARD_VILLA_LIST}`;
export const PATH_AGENT_DASHBOARD_VILLA_EDIT = "villa/edit";
export const PATH_AGENT_DASHBOARD_VILLA_EDIT_ABSOLUTE = `${PATH_AGENT_DASHBOARD}/${PATH_AGENT_DASHBOARD_PROPERTY}/${PATH_AGENT_DASHBOARD_VILLA_EDIT}`;
export const PATH_AGENT_DASHBOARD_VILLA_DETAIL = "villa/detail";
export const PATH_AGENT_DASHBOARD_VILLA_DETAIL_ABSOLUTE = `${PATH_AGENT_DASHBOARD}/${PATH_AGENT_DASHBOARD_PROPERTY}/${PATH_AGENT_DASHBOARD_VILLA_DETAIL}`;

// CONDOMINIUM
export const PATH_AGENT_DASHBOARD_CONDOMINIUM_LIST = "condominium/list";
export const PATH_AGENT_DASHBOARD_CONDOMINIUM_LIST_ABSOLUTE = `${PATH_AGENT_DASHBOARD}/${PATH_AGENT_DASHBOARD_PROPERTY}/${PATH_AGENT_DASHBOARD_CONDOMINIUM_LIST}`;
export const PATH_AGENT_DASHBOARD_CONDOMINIUM_EDIT = "condominium/edit";
export const PATH_AGENT_DASHBOARD_CONDOMINIUM_EDIT_ABSOLUTE = `${PATH_AGENT_DASHBOARD}/${PATH_AGENT_DASHBOARD_PROPERTY}/${PATH_AGENT_DASHBOARD_CONDOMINIUM_EDIT}`;
export const PATH_AGENT_DASHBOARD_CONDOMINIUM_DETAIL = "condominium/detail";
export const PATH_AGENT_DASHBOARD_CONDOMINIUM_DETAIL_ABSOLUTE = `${PATH_AGENT_DASHBOARD}/${PATH_AGENT_DASHBOARD_PROPERTY}/${PATH_AGENT_DASHBOARD_CONDOMINIUM_DETAIL}`;

// TRADITIONAL HOUSE
export const PATH_AGENT_DASHBOARD_TRADITIONAL_HOUSE_LIST =
  "traditionalhouse/list";
export const PATH_AGENT_DASHBOARD_TRADITIONAL_HOUSE_LIST_ABSOLUTE = `${PATH_AGENT_DASHBOARD}/${PATH_AGENT_DASHBOARD_PROPERTY}/${PATH_AGENT_DASHBOARD_TRADITIONAL_HOUSE_LIST}`;
export const PATH_AGENT_DASHBOARD_TRADITIONAL_HOUSE_EDIT =
  "traditionalhouse/edit";
export const PATH_AGENT_DASHBOARD_TRADITIONAL_HOUSE_EDIT_ABSOLUTE = `${PATH_AGENT_DASHBOARD}/${PATH_AGENT_DASHBOARD_PROPERTY}/${PATH_AGENT_DASHBOARD_TRADITIONAL_HOUSE_EDIT}`;
export const PATH_AGENT_DASHBOARD_TRADITIONAL_HOUSE_DETAIL =
  "traditionalhouse/detail";
export const PATH_AGENT_DASHBOARD_TRADITIONAL_HOUSE_DETAIL_ABSOLUTE = `${PATH_AGENT_DASHBOARD}/${PATH_AGENT_DASHBOARD_PROPERTY}/${PATH_AGENT_DASHBOARD_TRADITIONAL_HOUSE_DETAIL}`;

//COMMERCIAL PROPERTY
export const PATH_AGENT_DASHBOARD_COMMERCIALPROPERTY_LIST =
  "commercialproperty/list";
export const PATH_AGENT_DASHBOARD_COMMERCIALPROPERTY_LIST_ABSOLUTE = `${PATH_AGENT_DASHBOARD}/${PATH_AGENT_DASHBOARD_PROPERTY}/${PATH_AGENT_DASHBOARD_COMMERCIALPROPERTY_LIST}`;
export const PATH_AGENT_DASHBOARD_COMMERCIALPROPERTY_EDIT =
  "commercialproperty/edit";
export const PATH_AGENT_DASHBOARD_COMMERCIALPROPERTY_EDIT_ABSOLUTE = `${PATH_AGENT_DASHBOARD}/${PATH_AGENT_DASHBOARD_PROPERTY}/${PATH_AGENT_DASHBOARD_COMMERCIALPROPERTY_EDIT}`;
export const PATH_AGENT_DASHBOARD_COMMERCIALPROPERTY_DETAIL =
  "commercialproperty/detail";
export const PATH_AGENT_DASHBOARD_COMMERCIALPROPERTY_DETAIL_ABSOLUTE = `${PATH_AGENT_DASHBOARD}/${PATH_AGENT_DASHBOARD_PROPERTY}/${PATH_AGENT_DASHBOARD_COMMERCIALPROPERTY_DETAIL}`;

//COMMERCIAL PROPERTY UNIT
export const PATH_AGENT_DASHBOARD_COMMERCIALPROPERTYUNIT_DETAIL =
  "commercialpropertyunit/detail";
export const PATH_AGENT_DASHBOARD_COMMERCIALPROPERTYUNIT_DETAIL_ABSOLUTE = `${PATH_AGENT_DASHBOARD}/${PATH_AGENT_DASHBOARD_PROPERTY}/${PATH_AGENT_DASHBOARD_COMMERCIALPROPERTYUNIT_DETAIL}`;
export const PATH_AGENT_DASHBOARD_COMMERCIALPROPERTYUNIT_EDIT =
  "commercialpropertyunit/edit";
export const PATH_AGENT_DASHBOARD_COMMERCIALPROPERTYUNIT_EDIT_ABSOLUTE = `${PATH_AGENT_DASHBOARD}/${PATH_AGENT_DASHBOARD_PROPERTY}/${PATH_AGENT_DASHBOARD_COMMERCIALPROPERTYUNIT_EDIT}`;

//SHAREHOUSE
export const PATH_AGENT_DASHBOARD_SHAREHOUSE_EDIT = "sharehouse/edit";
export const PATH_AGENT_DASHBOARD_SHAREHOUSE_EDIT_ABSOLUTE = `${PATH_AGENT_DASHBOARD}/${PATH_AGENT_DASHBOARD_PROPERTY}/${PATH_AGENT_DASHBOARD_SHAREHOUSE_EDIT}`;
export const PATH_AGENT_DASHBOARD_SHAREHOUSE_LIST = "sharehouse/list";
export const PATH_AGENT_DASHBOARD_SHAREHOUSE_LIST_ABSOLUTE = `${PATH_AGENT_DASHBOARD}/${PATH_AGENT_DASHBOARD_PROPERTY}/${PATH_AGENT_DASHBOARD_SHAREHOUSE_LIST}`;
export const PATH_AGENT_DASHBOARD_SHAREHOUSE_DETAIL = "sharehouse/detail";
export const PATH_AGENT_DASHBOARD_SHAREHOUSE_DETAIL_ABSOLUTE = `${PATH_AGENT_DASHBOARD}/${PATH_AGENT_DASHBOARD_PROPERTY}/${PATH_AGENT_DASHBOARD_SHAREHOUSE_DETAIL}`;

//SHAREHOUSE
export const PATH_AGENT_DASHBOARD_OFFICE_EDIT = "office/edit";
export const PATH_AGENT_DASHBOARD_OFFICE_EDIT_ABSOLUTE = `${PATH_AGENT_DASHBOARD}/${PATH_AGENT_DASHBOARD_PROPERTY}/${PATH_AGENT_DASHBOARD_OFFICE_EDIT}`;
export const PATH_AGENT_DASHBOARD_OFFICE_LIST = "office/list";
export const PATH_AGENT_DASHBOARD_OFFICE_LIST_ABSOLUTE = `${PATH_AGENT_DASHBOARD}/${PATH_AGENT_DASHBOARD_PROPERTY}/${PATH_AGENT_DASHBOARD_OFFICE_LIST}`;
export const PATH_AGENT_DASHBOARD_OFFICE_DETAIL = "office/detail";
export const PATH_AGENT_DASHBOARD_OFFICE_DETAIL_ABSOLUTE = `${PATH_AGENT_DASHBOARD}/${PATH_AGENT_DASHBOARD_PROPERTY}/${PATH_AGENT_DASHBOARD_OFFICE_DETAIL}`;

//LAND
export const PATH_AGENT_DASHBOARD_LAND_EDIT = "land/edit";
export const PATH_AGENT_DASHBOARD_LAND_EDIT_ABSOLUTE = `${PATH_AGENT_DASHBOARD}/${PATH_AGENT_DASHBOARD_PROPERTY}/${PATH_AGENT_DASHBOARD_LAND_EDIT}`;
export const PATH_AGENT_DASHBOARD_LAND_LIST = "land/list";
export const PATH_AGENT_DASHBOARD_LAND_LIST_ABSOLUTE = `${PATH_AGENT_DASHBOARD}/${PATH_AGENT_DASHBOARD_PROPERTY}/${PATH_AGENT_DASHBOARD_LAND_LIST}`;
export const PATH_AGENT_DASHBOARD_LAND_DETAIL = "land/detail";
export const PATH_AGENT_DASHBOARD_LAND_DETAIL_ABSOLUTE = `${PATH_AGENT_DASHBOARD}/${PATH_AGENT_DASHBOARD_PROPERTY}/${PATH_AGENT_DASHBOARD_LAND_DETAIL}`;

//HALL
export const PATH_AGENT_DASHBOARD_HALL_EDIT = "hall/edit";
export const PATH_AGENT_DASHBOARD_HALL_EDIT_ABSOLUTE = `${PATH_AGENT_DASHBOARD}/${PATH_AGENT_DASHBOARD_PROPERTY}/${PATH_AGENT_DASHBOARD_HALL_EDIT}`;
export const PATH_AGENT_DASHBOARD_HALL_LIST = "hall/list";
export const PATH_AGENT_DASHBOARD_HALL_LIST_ABSOLUTE = `${PATH_AGENT_DASHBOARD}/${PATH_AGENT_DASHBOARD_PROPERTY}/${PATH_AGENT_DASHBOARD_HALL_LIST}`;
export const PATH_AGENT_DASHBOARD_HALL_DETAIL = "hall/detail";
export const PATH_AGENT_DASHBOARD_HALL_DETAIL_ABSOLUTE = `${PATH_AGENT_DASHBOARD}/${PATH_AGENT_DASHBOARD_PROPERTY}/${PATH_AGENT_DASHBOARD_HALL_DETAIL}`;

//COMMERCIAL PROPERTY
export const PATH_AGENT_DASHBOARD_ALLPURPOSEPROPERTY_LIST =
  "allpurposeproperty/list";
export const PATH_AGENT_DASHBOARD_ALLPURPOSEPROPERTY_LIST_ABSOLUTE = `${PATH_AGENT_DASHBOARD}/${PATH_AGENT_DASHBOARD_PROPERTY}/${PATH_AGENT_DASHBOARD_ALLPURPOSEPROPERTY_LIST}`;
export const PATH_AGENT_DASHBOARD_ALLPURPOSEPROPERTY_EDIT =
  "allpurposeproperty/edit";
export const PATH_AGENT_DASHBOARD_ALLPURPOSEPROPERTY_EDIT_ABSOLUTE = `${PATH_AGENT_DASHBOARD}/${PATH_AGENT_DASHBOARD_PROPERTY}/${PATH_AGENT_DASHBOARD_ALLPURPOSEPROPERTY_EDIT}`;
export const PATH_AGENT_DASHBOARD_ALLPURPOSEPROPERTY_DETAIL =
  "allpurposeproperty/detail";
export const PATH_AGENT_DASHBOARD_ALLPURPOSEPROPERTY_DETAIL_ABSOLUTE = `${PATH_AGENT_DASHBOARD}/${PATH_AGENT_DASHBOARD_PROPERTY}/${PATH_AGENT_DASHBOARD_ALLPURPOSEPROPERTY_DETAIL}`;

//COMMERCIAL PROPERTY UNIT
export const PATH_AGENT_DASHBOARD_ALLPURPOSEPROPERTYUNIT_DETAIL =
  "allpurposepropertyunit/detail";
export const PATH_AGENT_DASHBOARD_ALLPURPOSEPROPERTYUNIT_DETAIL_ABSOLUTE = `${PATH_AGENT_DASHBOARD}/${PATH_AGENT_DASHBOARD_PROPERTY}/${PATH_AGENT_DASHBOARD_ALLPURPOSEPROPERTYUNIT_DETAIL}`;
export const PATH_AGENT_DASHBOARD_ALLPURPOSEPROPERTYUNIT_EDIT =
  "allpurposepropertyunit/edit";
export const PATH_AGENT_DASHBOARD_ALLPURPOSEPROPERTYUNIT_EDIT_ABSOLUTE = `${PATH_AGENT_DASHBOARD}/${PATH_AGENT_DASHBOARD_PROPERTY}/${PATH_AGENT_DASHBOARD_ALLPURPOSEPROPERTYUNIT_EDIT}`;

//LISTING
export const PATH_AGENT_DASHBOARD_LISTING_DETAIL = "listing/detail";
export const PATH_AGENT_DASHBOARD_LISTING_DETAIL_ABSOLUTE = `${PATH_AGENT_DASHBOARD}/${PATH_AGENT_DASHBOARD_PROPERTY}/${PATH_AGENT_DASHBOARD_LISTING_DETAIL}`;
export const PATH_AGENT_DASHBOARD_LISTING_LIST = "listing/list";
export const PATH_AGENT_DASHBOARD_LISTING_LIST_ABSOLUTE = `${PATH_AGENT_DASHBOARD}/${PATH_AGENT_DASHBOARD_PROPERTY}/${PATH_AGENT_DASHBOARD_LISTING_LIST}`;
export const PATH_AGENT_DASHBOARD_LISTING_ADD = "listing/add";
export const PATH_AGENT_DASHBOARD_LISTING_ADD_ABSOLUTE = `${PATH_AGENT_DASHBOARD}/${PATH_AGENT_DASHBOARD_PROPERTY}/${PATH_AGENT_DASHBOARD_LISTING_ADD}`;
export const PATH_AGENT_DASHBOARD_LISTING_EDIT = "listing/edit";
export const PATH_AGENT_DASHBOARD_LISTING_EDIT_ABSOLUTE = `${PATH_AGENT_DASHBOARD}/${PATH_AGENT_DASHBOARD_PROPERTY}/${PATH_AGENT_DASHBOARD_LISTING_EDIT}`;

export const PATH_AGENT_DASHBOARD_FEATURE_LISTING = "listing/feature";
export const PATH_AGENT_DASHBOARD_FEATURE_LISTING_ABSOLUTE = `${PATH_AGENT_DASHBOARD}/${PATH_AGENT_DASHBOARD_PROPERTY}/${PATH_AGENT_DASHBOARD_FEATURE_LISTING}`;

//PUBLIC LISTING PAGE
export const PATH_PUBLIC_LISTING = "/public/listing";
export const PATH_PUBLIC_LISTING_DETAIL = ":listingId/detail";
export const PATH_SAVED_LISTINGS = "saved";
export const PATH_SAVED_LISTINGS_ABSOLUTE = `${PATH_PUBLIC_LISTING}/${PATH_SAVED_LISTINGS}`;

export const PATH_LISTING_IMAGE_VIEW = ":listingId/image/view";
export const PATH_LISTING_VIDEO_VIEW = ":listingId/video/view";
// export const PATH_LISTING_IMAGE_VIEW_ABSOLUTE = `${PATH_PUBLIC_LISTING}/${PATH_LISTING_IMAGE_VIEW}`;

// export const PATH_PUBLIC_LISTING_DETAIL_ABSOLUTE = `${PATH_PUBLIC_LISTING}/${PATH_PUBLIC_LISTING_DETAIL}`;

//==============================================================================================

export const PATH_AGENT_DASHBOARD_PROPERTY_LIST_ABSOLUTE = `${PATH_AGENT_DASHBOARD}/${PATH_AGENT_DASHBOARD_PROPERTY}/${PATH_AGENT_DASHBOARD_PROPERTY_LIST}`;
export const PATH_AGENT_DASHBOARD_PROPERTY_DETAIL = "detail";
export const PATH_AGENT_DASHBOARD_PROPERTY_DETAIL_ABSOLUTE = `${PATH_AGENT_DASHBOARD}/${PATH_AGENT_DASHBOARD_PROPERTY}/${PATH_AGENT_DASHBOARD_PROPERTY_DETAIL}`;
export const PATH_AGENT_DASHBOARD_PROPERTY_FILE_UPLOAD = "file/upload";
export const PATH_AGENT_DASHBOARD_PROPERTY_FILE_UPLOAD_ABSOLUTE = `${PATH_AGENT_DASHBOARD}/${PATH_AGENT_DASHBOARD_PROPERTY}/${PATH_AGENT_DASHBOARD_PROPERTY_FILE_UPLOAD}`;
export const PATH_AGENT_DASHBOARD_PROPERTY_EDIT = "edit";
export const PATH_AGENT_DASHBOARD_PROPERTY_EDIT_ABSOLUTE = `${PATH_AGENT_DASHBOARD}/${PATH_AGENT_DASHBOARD_PROPERTY}/${PATH_AGENT_DASHBOARD_PROPERTY_EDIT}`;

export const PATH_AGENT_DASHBOARD_PROPERTY_ADDRESS_EDIT = "address/edit";
export const PATH_AGENT_DASHBOARD_PROPERTY_ADDRESS_EDIT_ABSOLUTE = `${PATH_AGENT_DASHBOARD}/${PATH_AGENT_DASHBOARD_PROPERTY}/${PATH_AGENT_DASHBOARD_PROPERTY_ADDRESS_EDIT}`;

export const PATH_AGENT_DASHBOARD_EDUCATION_FACILITY_ADD = "edufa/add";
export const PATH_AGENT_DASHBOARD_EDUCATION_FACILITY_ADD_ABSOLUTE = `${PATH_AGENT_DASHBOARD}/${PATH_AGENT_DASHBOARD_PROPERTY}/${PATH_AGENT_DASHBOARD_EDUCATION_FACILITY_ADD}`;

export const PATH_AGENT_DASHBOARD_TRANSPORT_FACILITY_ADD = "tranfa/add";
// export const PATH_AGENT_DASHBOARD_TRANSPORT_FACILITY_ADD_ABSOLUTE = `${PATH_AGENT_DASHBOARD}/${PATH_AGENT_DASHBOARD_PROPERTY}/${PATH_AGENT_DASHBOARD_TRANSPORT_FACILITY_ADD}`;

export const PATH_AGENT_DASHBOARD_POI_ADD = "poi/add";

export const PATH_AGENT_DASHBOARD_AMENITY_ADD = "amenity/add";

export const PATH_AGENT_DASHBOARD_PROPERTY_RULE_ADD = "rule/add";

//PROPERTIES
export const PATH_PROPERTY_HOME = "/property";
export const PATH_PROPERTY_ADD = "add";
export const PATH_PROPERTY_ADD_ABSOLUTE = `${PATH_PROPERTY_HOME}/${PATH_PROPERTY_ADD}`;
export const PATH_PROPERTY_FILE_UPLOAD = "file/upload";
export const PATH_PROPERTY_FILE_UPLOAD_ABSOLUTE = `${PATH_PROPERTY_HOME}/${PATH_PROPERTY_FILE_UPLOAD}`;

//PROPERTY CATEGORY KEYS USED FOR BACKEND AND FRONTEND SYNCHRONIZATION
export const APARTMENT_KEY = "CAT001";
export const CONDOMINIUM_KEY = "CAT002";
export const TRADITIONAL_HOUSE_KEY = "CAT003";
export const VILLA_KEY = "CAT004";
export const SHARE_HOUSE_KEY = "CAT005";
export const COMMERCIAL_PROPERTY_KEY = "CAT006";
export const OFFICE_KEY = "CAT007";
export const HALL_KEY = "CAT008";
export const LAND_KEY = "CAT009";
export const ALL_PURPOSE_PROPERTY_KEY = "CAT010";

//PAYMENT METHOD KEYS USED FOR BACKEND AND FRONTEND SYNCHRONIZATION
export const CASH_KEY = "PM01";
export const BANK_TRANSFER_KEY = "PM02";
export const CREDIT_CARD_KEY = "PM03";
export const SUBSCRIPTION_KEY = "PM04";
export const COUPON_KEY = "PM05";
export const MOBILE_KEY = "PM06";

//LISTING TYPES
export const RENT_LISTING_TYPE = "RENT";
export const SALE_LISTING_TYPE = "SALE";

//LISTING KEYS
export const LISTING_KEY_BY_AGENT = "byAgent";
export const LISTING_KEY_BY_PROPERTY = "byProperty";
export const LISTING_KEY_BY_UNIT = "byUnit";

//SYSTEM ASSET OWNER NAMES

export const ASSET_APARTMENT_PICTURE = "APARTMENT_PICTURE";
export const ASSET_VILLA_PICTURE = "VILLA_PICTURE";
export const ASSET_CONDOMINIUM_PICTURE = "CONDOMINIUM_PICTURE";
export const ASSET_TRADITIONAL_HOUSE_PICTURE = "TRADITIONAL_HOUSE_PICTURE";
export const ASSET_SHARE_HOUSE_PICTURE = "SHARE_HOUSE_PICTURE";
export const ASSET_COMMERCIAL_PROPERTY_PICTURE = "COMMERCIAL_PROPERTY_PICTURE";
export const ASSET_OFFICE_PICTURE = "OFFICE_PICTURE";
export const ASSET_HALL_PICTURE = "HALL_PICTURE";
export const ASSET_LAND_PICTURE = "LAND_PICTURE";
export const ASSET_ALL_PURPOSE_PROPERTY_PICTURE =
  "ALL_PURPOSE_PROPERTY_PICTURE";
export const ASSET_LANDING_PAGE_SLIDER = "LANDING_PAGE_SLIDER";
